use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum RPCEvent {
  CurrentUserUpdate,
  GuildStatus,
  GuildCreate,
  ChannelCreate,
  RelationshipUpdate,
  VoiceChannelSelect,
  VoiceStateCreate,
  VoiceStateDelete,
  VoiceStateUpdate,
  VoiceSettingsUpdate,
  VoiceConnectionStatus,
  SpeakingStart,
  SpeakingStop,
  GameJoin,
  GameSpectate,
  ActivityJoin,
  ActivityJoinRequest,
  ActivitySpectate,
  ActivityInvite,
  NotificationCreate,
  MessageCreate,
  MessageUpdate,
  MessageDelete,
  LobbyDelete,
  LobbyUpdate,
  LobbyMemberConnect,
  LobbyMemberDisconnect,
  LobbyMemberUpdate,
  LobbyMessage,
  CaptureShortcutChange,
  Overlay,
  OverlayUpdate,
  EntitlementCreate,
  EntitlementDelete,
  UserAchievementUpdate,
  Ready,
  Error,
}
